"""Schemas package."""

from ai_service.schemas.document import (
    DocumentInputSchema,
    DocumentStatusEnum,
    DocumentTypeEnum,
    DocumentValidationResponse,
)
from ai_service.schemas.errors import ErrorResponse
from ai_service.schemas.health import HealthResponse
from ai_service.schemas.verification import (
    BeneficiaryComparison,
    ChangeCategory,
    CommitmentComparison,
    CSRChangeDetectionRequest,
    CSRChangeDetectionResult,
    CSRChangeItem,
    CSRDimensionsComparison,
    CSRDocumentProfile,
    CSREvidenceReference,
    CSRProjectSnapshot,
    DocumentSummaryHeader,
    GeographyComparison,
    PolicyComparison,
    ProjectComparison,
    ProjectSemanticMatch,
    SpendingComparison,
    SpendingComparisonItem,
    VerificationConfidence,
    WASHDirection,
    WASHFocusComparison,
)

from ai_service.schemas.freshness import (
    FreshnessAssessment,
    FreshnessCalculationRequest,
    FreshnessHistoryResponse,
    FreshnessStatus,
    SourceFreshnessRecord,
    SourceType,
)
from ai_service.schemas.scoring import (
    BatchScoringRequest,
    BatchScoringResponse,
    CandidateScoringInput,
    LeadScore,
    PriorityBand,
    ScoreComponentItem,
    ScoringComponentsBreakdown,
)

from ai_service.schemas.copilot import (
    CopilotChatRequest,
    CopilotChatResponse,
    RecommendationAction,
    RecommendationHistoryResponse,
    RecommendationRequest,
    RecommendationResult,
)
from ai_service.schemas.outreach import (
    ApproveDraftRequest,
    ClaimValidationResult,
    CompanyOutreachContext,
    DraftRevision,
    EditDraftRequest,
    GenerateDraftRequest,
    OutreachApprovalStatus,
    OutreachDraft,
    SendAuditRecord,
    SendDraftRequest,
)

__all__ = [
    "HealthResponse",
    "ErrorResponse",
    "DocumentInputSchema",
    "DocumentTypeEnum",
    "DocumentStatusEnum",
    "DocumentValidationResponse",
    "ChangeCategory",
    "WASHDirection",
    "VerificationConfidence",
    "CSREvidenceReference",
    "CSRProjectSnapshot",
    "CSRDocumentProfile",
    "SpendingComparisonItem",
    "SpendingComparison",
    "WASHFocusComparison",
    "ProjectSemanticMatch",
    "ProjectComparison",
    "GeographyComparison",
    "BeneficiaryComparison",
    "CommitmentComparison",
    "PolicyComparison",
    "CSRChangeItem",
    "CSRDimensionsComparison",
    "DocumentSummaryHeader",
    "CSRChangeDetectionResult",
    "CSRChangeDetectionRequest",
    "FreshnessStatus",
    "SourceType",
    "SourceFreshnessRecord",
    "FreshnessAssessment",
    "FreshnessHistoryResponse",
    "FreshnessCalculationRequest",
    "PriorityBand",
    "ScoreComponentItem",
    "ScoringComponentsBreakdown",
    "CandidateScoringInput",
    "LeadScore",
    "BatchScoringRequest",
    "BatchScoringResponse",
    "RecommendationAction",
    "RecommendationRequest",
    "RecommendationResult",
    "RecommendationHistoryResponse",
    "CopilotChatRequest",
    "CopilotChatResponse",
    "OutreachApprovalStatus",
    "CompanyOutreachContext",
    "ClaimValidationResult",
    "DraftRevision",
    "OutreachDraft",
    "GenerateDraftRequest",
    "EditDraftRequest",
    "ApproveDraftRequest",
    "SendDraftRequest",
    "SendAuditRecord",
]



